"bug: incorrect behavior":
  - "### What type of problem is this\\?\\n\\nIncorrect behavior"
"bug: missing behavior":
  - "### What type of problem is this\\?\\n\\nMissing behavior"
"bug: crash/freeze":
  - "### What type of problem is this\\?\\n\\nCrash or freeze"
"bug: regression":
  - "### What type of problem is this\\?\\n\\nRegression"
