"bug: incorrect behavior":
  - "### What type of problem is this\\?\\nIncorrect behavior"
"bug: missing behavior":
  - "### What type of problem is this\\?\\nMissing behavior"
"bug: crash/freeze":
  - "### What type of problem is this\\?\\nCrash or freeze"
"bug: regression":
  - "### What type of problem is this\\?\\nRegression"
