#!/bin/sh

# ------------ Lint staged files ------------
printf "\n\n\n[1mLinting...[0m\n"
FORCE_COLOR=1 bunx lint-staged

# ---------------- Run tests ----------------
printf "\n\n\n[1mTesting...[0m\n"
FORCE_COLOR=1 bun test

# ----------------- Finish ------------------
exit 0
